// This file is generated by FBC.

#include "bfb_ess_battery.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void bfb_ess_batteryinit(bfb_ess_battery* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
    me->Charge_Power = 1;
    me->_Charge_Power = 1;
}

/* ECC algorithms */
void bfb_ess_battery_bat_model_algo(bfb_ess_battery* me)
{
REAL SoC = me->SoC_input;
REAL discharge = me->Discharge_Power;
REAL cb = 620;// kwh from Kalpesh code, power required by ESS to charge 100% in 1 hour i.e 1C rate
REAL Demand = me->Power_Demand;
me->Demand = Demand;

me->BatterySoC = SoC - (discharge*100/(cb*60));
SoC = SoC - (discharge*100/(cb*60));
printf("SoC_discharge : %f  \r\n",me->BatterySoC);

//Have better modelling
//current_SoC += me->Minutes_per_tick * me->Current_A; //WRONG: Fix 

//#define MAX_SOC 100
//#define MIN_SOC 0

//if(current_SoC > MAX_SOC) {
 //current_SoC = MAX_SOC;
//} else if (current_SoC < MIN_SOC) {
 //current_SoC = MIN_SOC;
//}

//me->Current_SoC = current_SoC;
}

void bfb_ess_battery_Algorithm1(bfb_ess_battery* me)
{
REAL SoC = me->SoC_input;
REAL charge = me->Charge_Power;
REAL Demand = me->Power_Demand;
me->Demand = Demand;

REAL cb = 620;// kwh from Kalpesh code, power required by ESS to charge 100% in 1 hour i.e 1C rate
me->BatterySoC = SoC + charge*100/(cb*60);
SoC = SoC + charge*100/(cb*60);
printf("SoC_charge : %f  \r\n",me->BatterySoC);

}

void bfb_ess_battery_Algorithm2(bfb_ess_battery* me)
{
//static REAL SoC = 0;
printf("welcome to soc initial \r\n");
me->BatterySoC = me->SoC_input;

REAL Demand = me->Power_Demand;
me->Demand = Demand;
printf("power : %f, %f \r\n", Demand, me->Power_Demand);

}

/* Function block execution function */
void bfb_ess_batteryrun(bfb_ess_battery* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.Tick_ESS) {
            me->Discharge_Power = me->_Discharge_Power;
            me->Charge_Power = me->_Charge_Power;
            me->SoC_input = me->_SoC_input;
            me->Power_Demand = me->_Power_Demand;
        }
    }
    for (;;) {
        switch (me->_state) {
            case 0:
                // State: Init
                if (!me->_entered) {
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Do_nothing && me->_input.event.Tick_ESS) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charge && me->_input.event.Tick_ESS) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Discharge && me->_input.event.Tick_ESS) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 1:
                // State: Do_nothing
                if (!me->_entered) {
                    bfb_ess_battery_Algorithm2(me);
                    me->_output.event.SoC_change = 1;
                    me->_output.event.Do_nothing_out = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Discharge && me->_input.event.Tick_ESS) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charge && me->_input.event.Tick_ESS) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Tick_ESS) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 2:
                // State: Discharging
                if (!me->_entered) {
                    bfb_ess_battery_bat_model_algo(me);
                    me->_output.event.SoC_change = 1;
                    me->_output.event.Discharge_out = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Charge && me->_input.event.Tick_ESS) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Tick_ESS) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Discharge && me->_input.event.Tick_ESS) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 3:
                // State: CHARGING
                if (!me->_entered) {
                    bfb_ess_battery_Algorithm1(me);
                    me->_output.event.SoC_change = 1;
                    me->_output.event.Charge_out = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Discharge && me->_input.event.Tick_ESS) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Tick_ESS) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charge && me->_input.event.Tick_ESS) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
        }
        break;
    }
    if (me->_output.event.SoC_change) {
        me->_BatterySoC = me->BatterySoC;
        me->_Demand = me->Demand;
    }

    me->_input.events = 0;
}

