// This file is generated by FBC.

#include "bfb_controller_um.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void bfb_controller_uminit(bfb_controller_um* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void bfb_controller_um_Algorithm1(bfb_controller_um* me)
{
me->Power_Charging = 200;
printf(" Controler Charging state  \r\n");
//me->SoC_out = me->SoC;
//printf("Power Charging: %f", me->Power_Charging);
REAL Day = me->day;
DINT Minute = me->minute;

REAL Demand = me->Power_Demand;
me->Demand = Demand;
printf("Minute = %d Demand = %f",Minute, Demand);

if (Minute == 0 && Day == 0){
me->SoC = 90;
}
else{
me->SoC_out = me->SoC;
}
}

void bfb_controller_um_Algorithm2(bfb_controller_um* me)
{
REAL Power_required = me->Power_Demand;
REAL max_ESS_discharge = 150;
REAL Day = me->day;
DINT Minute = me->minute;
REAL Demand = me->Power_Demand;
me->Demand = Demand;

printf("Minute = %d Demand = %f",Minute, Demand);
if (max_ESS_discharge >  Power_required){
me->Power_Discharging = Power_required;
} 
else {
me->Power_Discharging = max_ESS_discharge;
}

if (Minute == 0 && Day == 0){
me->SoC = 90;
}
else{
me->SoC_out = me->SoC;
}
//me->SoC_out = me->SoC;
printf(" Disharging.... state..Controller \r\n ");
}

void bfb_controller_um_Algorithm3(bfb_controller_um* me)
{
REAL Power_required = me->Power_Demand;
REAL Peak = 130;
REAL max_ESS_discharge = 150;
REAL Day = me->day;
DINT Minute = me->minute;

printf("Minute1 = %d Demand1 = %f \r\n",Minute, Power_required);

if (Peak < Power_required){
 if (max_ESS_discharge > Power_required-Peak){
 me->Power_Discharging = Power_required - Peak;
 }
 else{
 me->Power_Discharging = max_ESS_discharge;
 }
}
else{
me->Power_Discharging = 0;
}
me->Demand = Power_required;
if (Minute == 0 && Day == 0){
me->SoC = 90;
}
else{
me->SoC_out = me->SoC;
}

//me->SoC_out = me->SoC;
printf(" Discharging.... state, OFFpeak controller \r\n ");
}

void bfb_controller_um_Algorithm4(bfb_controller_um* me)
{
REAL Day = me->day;
DINT Minute = me->minute;
printf("Do Nothing, controller \r\n");
REAL Demand = me->Power_Demand;
me->Demand = Demand;
printf("Minute = %d Demand = %f",Minute, Demand);
if (Minute == 0 && Day == 0){
//me->SoC = 0;
me->SoC_out = 90;
}
else{
me->SoC_out = me->SoC;
}

}

/* Function block execution function */
void bfb_controller_umrun(bfb_controller_um* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.Tick_controller) {
            me->SoC = me->_SoC;
            me->day = me->_day;
        }
        if (me->_input.event.tick) {
            me->Power_Demand = me->_Power_Demand;
            me->minute = me->_minute;
        }
    }
    for (;;) {
        switch (me->_state) {
            case 0:
                // State: init
                if (!me->_entered) {
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Tick_controller && ((me->SoC < 25 && (me->_input.event.Peak || me->_input.event.OffPeak)) || (me->SoC > 95 && me->_input.event.OffPeakCharge) || me->_input.event.Grey_area)) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeak) {
                        me->_state = 4;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeakCharge) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.Peak) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 1:
                // State: Do_nothing
                if (!me->_entered) {
                    bfb_controller_um_Algorithm4(me);
                    me->_output.event.Do_nothing = 1;
                    me->_output.event.Tick_time = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Tick_controller && me->_input.event.OffPeakCharge && (me->SoC < 95)) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.Peak && (me->SoC > 25)) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeak && (me->SoC > 25)) {
                        me->_state = 4;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && ((me->SoC < 25 && (me->_input.event.Peak || me->_input.event.OffPeak)) || (me->SoC > 95 && me->_input.event.OffPeakCharge) || me->_input.event.Grey_area)) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 2:
                // State: charging
                if (!me->_entered) {
                    bfb_controller_um_Algorithm1(me);
                    me->_output.event.Charging = 1;
                    me->_output.event.Tick_time = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Tick_controller && ((me->SoC < 25 && (me->_input.event.Peak || me->_input.event.OffPeak)) || (me->SoC > 95 && me->_input.event.OffPeakCharge))) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.Peak && (me->SoC > 25)) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeak && (me->SoC > 25)) {
                        me->_state = 4;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeakCharge && (me->SoC < 95)) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 3:
                // State: Peak
                if (!me->_entered) {
                    bfb_controller_um_Algorithm2(me);
                    me->_output.event.Discharging = 1;
                    me->_output.event.Tick_time = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Tick_controller && me->_input.event.OffPeak && (me->SoC > 25)) {
                        me->_state = 4;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeakCharge && (me->SoC < 95)) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && (me->_input.event.Grey_area || (me->SoC < 25 && (me->_input.event.Peak || me->_input.event.OffPeak)) || (me->SoC > 95 && me->_input.event.OffPeakCharge))) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.Peak && (me->SoC > 25)) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 4:
                // State: offPeak
                if (!me->_entered) {
                    bfb_controller_um_Algorithm3(me);
                    me->_output.event.Discharging = 1;
                    me->_output.event.Tick_time = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Tick_controller && me->_input.event.Peak && (me->SoC > 25)) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeakCharge && (me->SoC < 95)) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && ((me->SoC < 25 && (me->_input.event.Peak || me->_input.event.OffPeak)) || (me->SoC > 95 && me->_input.event.OffPeakCharge) || me->_input.event.Grey_area)) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Tick_controller && me->_input.event.OffPeak && (me->SoC > 25)) {
                        me->_state = 4;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
        }
        break;
    }
    if (me->_output.event.Tick_time) {
        me->_Power_Discharging = me->Power_Discharging;
        me->_Power_Charging = me->Power_Charging;
        me->_SoC_out = me->SoC_out;
        me->_Demand = me->Demand;
    }

    me->_input.events = 0;
}

