// This file is generated by FBC.

#ifndef BFB_ESS_BATTERY_H_
#define BFB_ESS_BATTERY_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT Discharge : 1; // 
        UDINT Charge : 1; // 
        UDINT Do_nothing : 1; // 
        UDINT Tick_ESS : 1; // 
    } event;
} bfb_ess_batteryIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT SoC_change : 1; // 
        UDINT Discharge_out : 1; // 
        UDINT Charge_out : 1; // 
        UDINT Do_nothing_out : 1; // 
    } event;
} bfb_ess_batteryOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    bfb_ess_batteryIEvents _input;
    REAL Discharge_Power; // 
    REAL _Discharge_Power;
    REAL Charge_Power; // 
    REAL _Charge_Power;
    REAL SoC_input; // 
    REAL _SoC_input;
    REAL Power_Demand; // 
    REAL _Power_Demand;
    bfb_ess_batteryOEvents _output;
    REAL BatterySoC; // 
    REAL _BatterySoC;
    REAL Demand; // 
    REAL _Demand;
} bfb_ess_battery;

/* Function block initialization function */
void bfb_ess_batteryinit(bfb_ess_battery* me);

/* Function block execution function */
void bfb_ess_batteryrun(bfb_ess_battery* me);

/* ECC algorithms */
void bfb_ess_battery_bat_model_algo(bfb_ess_battery* me);
void bfb_ess_battery_Algorithm1(bfb_ess_battery* me);
void bfb_ess_battery_Algorithm2(bfb_ess_battery* me);

#endif // BFB_ESS_BATTERY_H_
