// This file is generated by FBC.

#include "bfb_text_print.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void bfb_text_printinit(bfb_text_print* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void bfb_text_print_Algorithm1(bfb_text_print* me)
{
bool stop = me->Stop;
//static int l = 1440;
static DINT min[1442][7];
static REAL Power_Demand[1442][7];
static REAL Power_grid[1442][7];
static REAL Pb_charge[1442][7];
static REAL Pb_discharge[1442][7];
static REAL the_price[1442][7];
static REAL SoCess[1442][7];

static REAL Sma[1442][7];
static REAL Std_dev_arr[1442][7];

int day = me->Day;
int i = me->Min;

 min[i][day] = me->Min ;
 Power_Demand[i][day] = me->Demand;

 Power_grid[i][day] = me->Pgrid;

 Pb_charge[i][day] = me->Pbc;

 Pb_discharge[i][day] = me->Pbd;

 the_price[i][day] = me->Price;

SoCess[i][day] = me->SoC;

Sma[i][day] = me->SMA;
Std_dev_arr[i][day] = me->Std_dev;

 printf(" day print fbf = %d && min is %d \n",day, min[i][day]);

 //printf("Txt print min, %d, %d \r\n", min[i], me->Min);



if (stop){ //&& day == 6 && i == 1439
printf("Starting Excel File writing");
//printf("this is min 1 %d \n", min[0][0]);
FILE *f = fopen("Results.csv", "w");

if (f == NULL)
{
    printf("Error opening file!\n");
    exit(1);

}

/* print some text */
const char *text = " Minute,Demand,  Pgrid, Pbc, Pbd, Price_30_min, SoC,Sma,std, ,Minute,Demand,  Pgrid, Pbc, Pbd, Price_30_min, SoC,  ,Minute,Demand,  Pgrid, Pbc, Pbd, Price_30_min, SoC,  ,Minute,Demand,  Pgrid, Pbc, Pbd, Price_30_min, SoC,  ,Minute,Demand ,Pgrid, Pbc, Pbd, Price_30_min, SoC,  ,Minute,Demand ,Pgrid, Pbc, Pbd, Price_30_min, SoC,  ,Minute,Demand  ,Pgrid, Pbc, Pbd, Price_30_min, SoC";
fprintf(f, " %s \r\n", text);

for (DINT x=0; x < 1442; x++){
fprintf(f, " %d, %f, %f, %f, %f, %f, %f,%f,%f,  ,%d, %f, %f, %f, %f, %f, %f,  ,%d, %f, %f, %f, %f, %f, %f,  ,%d, %f, %f, %f, %f, %f, %f,  ,%d, %f, %f, %f, %f, %f, %f,  ,%d, %f, %f, %f, %f, %f, %f,  ,%d, %f, %f, %f, %f, %f, %f \n", min[x][0], Power_Demand[x][0], Power_grid[x][0], Pb_charge[x][0], Pb_discharge[x][0], the_price[x][0], SoCess[x][0],Sma[x][0],Std_dev_arr[x][0], min[x][1], Power_Demand[x][1], Power_grid[x][1], Pb_charge[x][1], Pb_discharge[x][1], the_price[x][1], SoCess[x][1], min[x][2], Power_Demand[x][2], Power_grid[x][2], Pb_charge[x][2], Pb_discharge[x][2], the_price[x][2], SoCess[x][2], min[x][3], Power_Demand[x][3], Power_grid[x][3], Pb_charge[x][3], Pb_discharge[x][3], the_price[x][3], SoCess[x][3], min[x][4], Power_Demand[x][4], Power_grid[x][4], Pb_charge[x][4], Pb_discharge[x][4], the_price[x][4], SoCess[x][4], min[x][5], Power_Demand[x][5], Power_grid[x][5], Pb_charge[x][5], Pb_discharge[x][5], the_price[x][5], SoCess[x][5], min[x][6], Power_Demand[x][6], Power_grid[x][6], Pb_charge[x][6], Pb_discharge[x][6], the_price[x][6], SoCess[x][6] );
}

fclose(f);

FILE *f2 =fopen("SMA.csv", "w");

if (f2 == NULL)
{
printf("Error opening file 2!\n");
    exit(1);
}

const char *text2 = " SMA, Std_dev, ,SMA, Std_dev, ,SMA, Std_dev, ,SMA, Std_dev, ,SMA, Std_dev, ,SMA, Std_dev, ,SMA, Std_dev";
for (DINT x=0; x < 1442; x++){
if (x%30 == 0){
fprintf(f, " %f, %f, ,%f, %f, ,%f, %f, ,%f, %f, ,%f, %f, ,%f, %f, ,%f, %f \n",Sma[x][0],Std_dev_arr[x][0],Sma[x][1],Std_dev_arr[x][1],Sma[x][2],Std_dev_arr[x][2],Sma[x][3],Std_dev_arr[x][3],Sma[x][4],Std_dev_arr[x][4],Sma[x][5],Std_dev_arr[x][5],Sma[x][6],Std_dev_arr[x][6]);
}
}

fclose(f);
exit(1);
}




}

/* Function block execution function */
void bfb_text_printrun(bfb_text_print* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.Tick_array) {
            me->Min = me->_Min;
            me->Demand = me->_Demand;
            me->Pgrid = me->_Pgrid;
            me->Pbc = me->_Pbc;
            me->Pbd = me->_Pbd;
            me->Price = me->_Price;
            me->lenght = me->_lenght;
            me->Day = me->_Day;
        }
        if (me->_input.event.tick_stop) {
            me->Stop = me->_Stop;
            me->SMA = me->_SMA;
            me->Std_dev = me->_Std_dev;
        }
        if (me->_input.event.Tick_SoC) {
            me->SoC = me->_SoC;
        }
    }
    for (;;) {
        if (me->_state == 0) {
            // State: Start
            if (!me->_entered) {
                me->_entered = true;
            }
            else {
                if (me->_input.event.Tick_array) {
                    me->_state = 1;
                    me->_entered = false;
                    continue;
                }
            }
        }
        else {
            // State: State1
            if (!me->_entered) {
                bfb_text_print_Algorithm1(me);
                me->_output.event.Done = 1;
                me->_entered = true;
            }
            else {
                me->_state = 0;
                me->_entered = false;
                continue;
            }
        }
        break;
    }

    me->_input.events = 0;
}

