// This file is generated by FBC.

#include "cfb_controller.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void cfb_controllerinit(cfb_controller* me)
{
    me->_input.events = 0;
    me->_output.events = 0;
    bfb_controller_uminit(&me->bfb_controller_um);
    bfb_off_peak_typesinit(&me->Reference);
}

/* Function block execution function */
void cfb_controllerrun(cfb_controller* me)
{
    me->bfb_controller_um._day = me->_day;
    me->bfb_controller_um._Power_Demand = me->_Demand_kWh;
    me->bfb_controller_um._SoC = me->_ESS_battery_SoC;
    me->bfb_controller_um._input.event.OffPeakCharge = me->Reference._output.event.Off_peak_charging;
    me->bfb_controller_um._input.event.Peak = me->Reference._output.event.Peak;
    me->bfb_controller_um._input.event.OffPeak = me->Reference._output.event.Off_peak;
    me->bfb_controller_um._minute = me->_Minute;
    me->bfb_controller_um._input.event.Tick_controller = me->Reference._output.event.Tick;
    me->bfb_controller_um._input.event.tick = me->_input.event.Tick;
    me->Reference._std_dev = me->_Std_dev;
    me->Reference._input.event.tick = me->_input.event.Tick;
    me->Reference._Sma = me->_Sma;
    me->Reference._price = me->_Price;
    
    bfb_controller_umrun(&me->bfb_controller_um);
    bfb_off_peak_typesrun(&me->Reference);
    
    me->_ESS_Charging_Power_Demand = me->bfb_controller_um._Power_Charging;
    me->_output.event.Charging = me->bfb_controller_um._output.event.Charging;
    me->_output.event.Do_nothing = me->bfb_controller_um._output.event.Do_nothing;
    me->_Demand = me->bfb_controller_um._Demand;
    me->_ESS_Discharging_Power = me->bfb_controller_um._Power_Discharging;
    me->_output.event.Discharging = me->bfb_controller_um._output.event.Discharging;
    me->_output.event.Tick_time = me->bfb_controller_um._output.event.Tick_time;
    me->_SoC = me->bfb_controller_um._SoC_out;
}
