// This file is generated by FBC.

#include "print.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void printinit(print* me)
{
    me->_state = 0;
    me->_entered = false;
    me->_input.events = 0;
    me->_output.events = 0;
}

/* ECC algorithms */
void print_do_print(print* me)
{
REAL ESS = me->ESS_Discharging_Power;
REAL Pg = me->Power_Demand - ESS;
REAL Power_Demand = me->Power_Demand;
REAL the_price = me->Price;
DINT minute = me->Minute;
printf("Minute in soc do_print %d \r\n", minute);
printf("the price do_print %f \r\n", the_price);
//if (Power_Demand == ESS){
//the_price = 0;
//}
//else if(Power_Demand == Pg){
//the_price = Pg * me->Price;
//}
me->min = minute;
me->Demand = Power_Demand;
me->Pgrid= Pg;
me->Pbc = 0;
me->Pbd = ESS;
me->Price_min = the_price / (30* 2* 1000);// converting $/Mwh to $/kwmin

printf("--------OUTPUT DISCHARGING STATE ------  \r\n");
//printf("DONE \r\n");
printf("Current Minute: %d\tCurrent Price:%f\r\n", me->Minute, the_price);
}

void print_Algorithm1(print* me)
{
REAL the_price = me->Price;
REAL ESS = 200;
REAL Pg = me->Power_Demand + ESS;
REAL Power_Demand = me->Power_Demand;
DINT minute = me->Minute;

me->min = minute;
me->Demand = Power_Demand;
me->Pgrid= Pg;
me->Pbc = ESS;
me->Pbd = 0;
me->Price_min = the_price / (30* 2* 1000);// converting $/Mwh to $/kwmin
printf("Minute in soc al1 %d \r\n", minute);


printf("-------- OUTPUT CHARGING STATE ----- \r\n");
printf("DONE \r\n");

//printf("Current Minute: %d\t Current Price:%f\r\n", me->Minute, me->Price);

//the_price = (Pg + ESS) * me->Price/(2*1000);//price / half kwh *1000
//printf(" Grid POWER: %f \t ESS Power:%f \r\n", Pg, ESS);
printf("Power demand: %f\t Current Price:%f\r\n", me->Power_Demand, the_price);
}

void print_Algorithm2(print* me)
{
REAL the_price = me->Price;
REAL ESS = 200;
REAL Pg = me->Power_Demand + ESS;
REAL Power_Demand = me->Power_Demand;
DINT minute = me->Minute;
printf("Minute in soc al2 %d \r\n", minute);

me->min = minute;
me->Demand = Power_Demand;
me->Pgrid= Power_Demand;
me->Pbc = 0;
me->Pbd = 0;
me->Price_min = the_price / (30* 2* 1000);// converting $/Mwh to $/kwmin

printf("----------NO CHARGE__NO DISCHARGE--------------- \r\n");
printf("DONE \r\n");
printf("Power Demand : %f\t Current Price:%f\r\n", Power_Demand, the_price);
}

/* Function block execution function */
void printrun(print* me)
{
    me->_output.events = 0;

    if (me->_input.events) {
        if (me->_input.event.Last_Tick) {
            me->Minute = me->_Minute;
            me->Price = me->_Price;
            me->Power_Demand = me->_Power_Demand;
            me->ESS_Charging = me->_ESS_Charging;
            me->ESS_Discharging_Power = me->_ESS_Discharging_Power;
        }
    }
    for (;;) {
        switch (me->_state) {
            case 0:
                // State: Init
                if (!me->_entered) {
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Do_nothing && me->_input.event.Last_Tick) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Discharging && me->_input.event.Last_Tick) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charging && me->_input.event.Last_Tick) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 1:
                // State: Do_nothing
                if (!me->_entered) {
                    print_Algorithm2(me);
                    me->_output.event.Done = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Discharging && me->_input.event.Last_Tick) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charging && me->_input.event.Last_Tick) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Last_Tick) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 2:
                // State: Discharging
                if (!me->_entered) {
                    print_do_print(me);
                    me->_output.event.Done = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Charging && me->_input.event.Last_Tick) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Last_Tick) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Discharging && me->_input.event.Last_Tick) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
            case 3:
                // State: Charging
                if (!me->_entered) {
                    print_Algorithm1(me);
                    me->_output.event.Done = 1;
                    me->_entered = true;
                }
                else {
                    if (me->_input.event.Discharging && me->_input.event.Last_Tick) {
                        me->_state = 2;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Do_nothing && me->_input.event.Last_Tick) {
                        me->_state = 1;
                        me->_entered = false;
                        continue;
                    }
                    else if (me->_input.event.Charging && me->_input.event.Last_Tick) {
                        me->_state = 3;
                        me->_entered = false;
                        continue;
                    }
                }
                break;
        }
        break;
    }
    if (me->_output.event.Done) {
        me->_min = me->min;
        me->_Demand = me->Demand;
        me->_Pgrid = me->Pgrid;
        me->_Pbc = me->Pbc;
        me->_Pbd = me->Pbd;
        me->_Price_min = me->Price_min;
    }

    me->_input.events = 0;
}

