// This file is generated by FBC.

#ifndef SIFB_BFB_INPUTS_H_
#define SIFB_BFB_INPUTS_H_

#include "fbtypes.h"

typedef union {
    UDINT events;
    struct {
        UDINT Start : 1; // 
    } event;
} sifb_bfb_inputsIEvents;

typedef union {
    UDINT events;
    struct {
        UDINT Tick : 1; // 
    } event;
} sifb_bfb_inputsOEvents;

typedef struct {
    UINT _state;
    BOOL _entered;
    sifb_bfb_inputsIEvents _input;
    sifb_bfb_inputsOEvents _output;
    DINT Minute; // 
    DINT _Minute;
    REAL Price; // 
    REAL _Price;
    REAL Demand_kWh; // 
    REAL _Demand_kWh;
    REAL Day; // 
    REAL _Day;
    INT Lenght; // 
    INT _Lenght;
    BOOL stop; // 
    BOOL _stop;
    REAL Sma; // 
    REAL _Sma;
    REAL Std_dev; // 
    REAL _Std_dev;
    DINT Var; // 
} sifb_bfb_inputs;

/* Function block initialization function */
void sifb_bfb_inputsinit(sifb_bfb_inputs* me);

/* Function block execution function */
void sifb_bfb_inputsrun(sifb_bfb_inputs* me);

/* ECC algorithms */
void sifb_bfb_inputs_input_sifb_algo(sifb_bfb_inputs* me);
void sifb_bfb_inputs_Algorithm1(sifb_bfb_inputs* me);

#endif // SIFB_BFB_INPUTS_H_
