// This file is generated by FBC.

#include "top_evstation.h"
#include <string.h>
#include <stdio.h>

/* Function block initialization function */
void top_evstationinit(top_evstation* me)
{
    sifb_bfb_inputsinit(&me->inputs);
    printinit(&me->Reference1);
    bfb_ess_batteryinit(&me->battery);
    cfb_controllerinit(&me->controller);
    bfb_text_printinit(&me->Reference);
}

/* Function block execution function */
void top_evstationrun(top_evstation* me)
{
    me->inputs._input.event.Start = me->Reference._output.event.Done;
    me->Reference1._input.event.Do_nothing = me->battery._output.event.Do_nothing_out;
    me->Reference1._Price = me->inputs._Price;
    me->Reference1._input.event.Charging = me->battery._output.event.Charge_out;
    me->Reference1._Minute = me->inputs._Minute;
    me->Reference1._ESS_Charging = me->controller._ESS_Charging_Power_Demand;
    me->Reference1._input.event.Discharging = me->battery._output.event.Discharge_out;
    me->Reference1._input.event.Last_Tick = me->battery._output.event.SoC_change;
    me->Reference1._Power_Demand = me->battery._Demand;
    me->Reference1._ESS_Discharging_Power = me->controller._ESS_Discharging_Power;
    me->battery._Power_Demand = me->controller._Demand;
    me->battery._input.event.Tick_ESS = me->controller._output.event.Tick_time;
    me->battery._input.event.Do_nothing = me->controller._output.event.Do_nothing;
    me->battery._Discharge_Power = me->controller._ESS_Discharging_Power;
    me->battery._Charge_Power = me->controller._ESS_Charging_Power_Demand;
    me->battery._SoC_input = me->controller._SoC;
    me->battery._input.event.Charge = me->controller._output.event.Charging;
    me->battery._input.event.Discharge = me->controller._output.event.Discharging;
    me->controller._ESS_battery_SoC = me->battery._BatterySoC;
    me->controller._day = me->inputs._Day;
    me->controller._Std_dev = me->inputs._Std_dev;
    me->controller._Demand_kWh = me->inputs._Demand_kWh;
    me->controller._Minute = me->inputs._Minute;
    me->controller._Sma = me->inputs._Sma;
    me->controller._Price = me->inputs._Price;
    me->controller._input.event.Tick = me->inputs._output.event.Tick;
    me->Reference._Demand = me->Reference1._Demand;
    me->Reference._Price = me->Reference1._Price_min;
    me->Reference._Pgrid = me->Reference1._Pgrid;
    me->Reference._input.event.Tick_SoC = me->battery._output.event.SoC_change;
    me->Reference._input.event.tick_stop = me->inputs._output.event.Tick;
    me->Reference._Pbc = me->Reference1._Pbc;
    me->Reference._Pbd = me->Reference1._Pbd;
    me->Reference._input.event.Tick_array = me->Reference1._output.event.Done;
    me->Reference._Min = me->Reference1._min;
    me->Reference._Day = me->inputs._Day;
    me->Reference._SMA = me->inputs._Sma;
    me->Reference._Stop = me->inputs._stop;
    me->Reference._SoC = me->battery._BatterySoC;
    me->Reference._Std_dev = me->inputs._Std_dev;
    me->Reference._lenght = me->inputs._Lenght;
    
    sifb_bfb_inputsrun(&me->inputs);
    printrun(&me->Reference1);
    bfb_ess_batteryrun(&me->battery);
    cfb_controllerrun(&me->controller);
    bfb_text_printrun(&me->Reference);
    
}
